Default map view 작성
wecode-bootcamp-korea/19-2nd-NoHomeOnlyMe-backend pull request #14
Opened 2021-05-04 11:04 UTC by Johnywhisky

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
saerch model / views.py 작성
		 
## 수정 사항들 자세한 내용
response.py > json response를 계산하는 모듈
 - 구/동에 해당하는 축척일 때 현재 보고있는 화면에 포함되는 데이터만 추출해 가공함

## 기타 질문 및 특이 사항
1. 더 효율적인 코드(?) 가 있을지 궁금합니다.
2. 아직 쿼리를 완전히 찍어보지 않아서 정참조 로직 vs 역참조 로직 중 어떤게 더 좋은지 확인은 못했습니다.
3. 테스트 코드는 추후 작성하겠습니다.
4. 포스트맨 테스트 결과
<img width="600" alt="스크린샷 2021-05-04 오후 6 28 34" src="https://user-images.githubusercontent.com/74827666/116994517-c7066100-ad13-11eb-8b39-171e1544cbc3.png">
<img width="601" alt="스크린샷 2021-05-04 오후 6 28 44" src="https://user-images.githubusercontent.com/74827666/116994519-c8d02480-ad13-11eb-8725-ecd384fa9141.png">
<img width="654" alt="스크린샷 2021-05-04 오후 7 57 49" src="https://user-images.githubusercontent.com/74827666/116994525-cbcb1500-ad13-11eb-9b15-3c695d18a5f0.png">

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-05-05 11:55 UTC, Kang-kyunghun requested changes

2021-05-05 11:55 UTC, Kang-kyunghun commented on search/views.py
> +class MapView(View):
코드 컨벤션 맞춰주세요.

2021-05-05 11:55 UTC, Kang-kyunghun commented on search/views.py
> +        except KeyError as e:
에러 메시지들 따로 관리하는 이유가 있나요?

2021-05-05 11:55 UTC, Kang-kyunghun commented on search/views.py
> +                    q |= Q(room_type__name = condition)
```suggestion
            if room_type:
                room_types  = room_type.split(',')
                q |= Q(room_type__name__in = room_type)
```
list를 한 번에 조건에 넣을 수 있는 방법입니다. 이 방법 참고해서 수정 가능한 부분들 수정해 주세요

2021-05-05 11:55 UTC, Kang-kyunghun commented on search/views.py
> +                MIN_DEPOSIT  = Decimal(deposit_list[0])
min값과 max값을 key 하나에 list로 받는 것 같은데, min값이나 max값 이 순서 바뀌거나 값이 하나가 빠졌을 때 뭐가 빠졌는지 판단하기 어려울 것 같습니다. 그래서 key을 나눠서 받는 것을 추천 드립니다. 프론트랑 이야기 해보세요.

2021-05-05 11:55 UTC, Kang-kyunghun commented on search/views.py
> +                zoom      = 16
zoom이 지도에서 볼 반경을 나타낼 것으로 보이는데, 이 값들도 상수처리 하는 것이 좋지 않을까 생각됩니다.

2021-05-05 12:00 UTC, Johnywhisky commented on search/views.py
> +class MapView(View):
넵

2021-05-05 12:00 UTC, Johnywhisky commented on search/views.py
> +        except KeyError as e:
앗 테스트 할 때 쓴건데, 지울게요!!

2021-05-05 13:30 UTC, Johnywhisky commented on search/views.py
> +                MIN_DEPOSIT  = Decimal(deposit_list[0])
필터적용 안될 때 -> 들어오는 값 없음
하나라도 있을 때 -> 최소, 최대 순서 로
프론트랑 얘기 맞춘 부분입니다!

2021-05-05 13:33 UTC, Johnywhisky commented on search/views.py
> +                    q |= Q(room_type__name = condition)
Q안에 배열을 넣어도 적용된단 말씀이시죠?? 쉘에서 테스트해보겠습니다~!

2021-05-05 13:35 UTC, Johnywhisky commented on search/views.py
> +                zoom      = 16
검색어 기능을 사용할 때 zoom값이 16으로 initializing되는데 이런 비슷한 경우에는 항상 상수처리 하는게 좋을 까요??

2021-05-05 23:43 UTC, Johnywhisky commented on search/views.py
> +                MIN_DEPOSIT  = Decimal(deposit_list[0])
생각해보니, 순서가 바뀔 수도 있으니까 이에 해당하는 경우는 처리하는게 좋을거 같네요...!

2021-05-06 03:00 UTC, Kang-kyunghun commented on search/views.py
> +                zoom      = 16
초기화 하는 값을 백엔드에서 정해 줄 수도 있지 않을까요?

2021-05-06 06:14 UTC, Johnywhisky commented on search/views.py
> +                zoom      = 16
넵

2021-05-06 09:00 UTC, Johnywhisky commented on search/views.py
> +                    q |= Q(room_type__name = condition)
Q안에 or조건으로 넣는 방법을 못찾았습니다!

2021-05-06 16:07 UTC, Johnywhisky commented on search/views.py
> +                    q |= Q(room_type__name = condition)
수정 완료!

2021-05-06 16:09 UTC, Johnywhisky commented
컨플릭트 해결 완료 / 리뷰 반영 완료

2021-05-06 17:04 UTC, Kang-kyunghun commented
고생 많으셨어요~!!

2021-05-06 17:04 UTC, merged